# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: simcrm_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: testUser
    ports:
      - "5432:5432"